### PR TITLE
Fix Invalid PathExpression error in ProxyQuery

### LINKED ISSUE #766: 3.2.0 composite key gives Invalid PathExpression, worked with 3.1.7
#### Sonata packages
```
$ ./composer.phar show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.28.0 3.28.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.8.0  3.8.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.7.1  3.7.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.0  2.3.0  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.2.0  3.2.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
```

#### Symfony packages
```
$ ./composer.phar show --latest 'symfony/*'
symfony/monolog-bundle     v3.1.2 v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v4.0.0 v4.0.0 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0 v1.6.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0 v1.6.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0 v1.6.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.6.0 v1.6.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0 v1.6.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.6.0 v1.6.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.1.6 v3.1.6 Symfony SwiftmailerBundle
symfony/symfony            v3.4.0 v3.4.0 The Symfony PHP framework

```

#### PHP version
```
$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

```

## Subject
I have a simple table with composite key which is consisting of relations to 2 other tables
```
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Store", inversedBy="stores")
     * @ORM\JoinColumn(nullable=false,onDelete="CASCADE")
     * @ORM\Id()
     * @ORM\GeneratedValue("NONE")
     * @var $store \AppBundle\Entity\Store
     */
    protected $store;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Product", inversedBy="products")
     * @ORM\JoinColumn(referencedColumnName="gtin",nullable=false,onDelete="CASCADE")
     * @ORM\Id()
     * @ORM\GeneratedValue("NONE")
     * @var $product \AppBundle\Entity\Product
     */
    protected $product;
```
Admin class is simple:
```
class StoreProductAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('store', 'entity', array(
                'class' => 'AppBundle\Entity\Store'
            ))
            ->add('product', 'entity', array(
                'class' => 'AppBundle\Entity\Product'
            ));
    }
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('store')
            ->add('product');
    }
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('store')
            ->addIdentifier('product');
    }
}
```
In services.yml the definition is as:
```
    sonata_admin.store_product:
        class: AppBundle\SonataAdmin\StoreProductAdmin
        arguments: [~, AppBundle\Entity\Store\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Store Product }
        public: true
```
Everything was great with v3.1.7 release but with v3.2.0  I am getting an error message about `Invalid PathExpression` when I go to table listing in SonataAdminBundle

## Steps to reproduce
Create a table with composite keys with ManyToOne relation. 
If I add a separate ID column, things work normally.

## Expected results
List of elements would be shown

## Actual results
```
Doctrine\ORM\Query\ QueryException
[Semantical Error] line 0, col 78 near 'store, o.product': Error: Invalid PathExpression. Must be a StateFieldPathExpression.

Doctrine\ORM\Query\ QueryException
SELECT DISTINCT IDENTITY(o.store) as store, IDENTITY(o.product) as product, o.store, o.product FROM AppBundle\Entity\Store\Product o LEFT JOIN o.store s_store LEFT JOIN o.product s_product ORDER BY o.store ASC, o.product ASC
```

### PR DESCRIPTION
**Pull request by dmarkowicz**
I am targeting this branch, because this is BC fix.

Closes #766

## Changelog

```markdown
### Fixed
- Fixed invalid PathExpression error in ProxyQuery
```

## Subject

#728 introduced bug in ProxyQuery for tables with composite keys. `ProxyQuery::addOrderedColumns` should skip columns that have already been added to the SELECT as IDENTITY(column).

### CODE REVIEW

**Comment by greg0ire** [comment]
Please format your commit message according to our rules : 

- The commit message subject must be less than 50 characters and tell us *what* you did.
- The commit message body should tell us *why* you did it. It is optional but highly recommended.

Bad example :

```
Fixed bug #989 by removing call to defraculate()
```

Good example:

```
Remove call to defraculate()

Calling this function caused a bug because it interferes 
with calls to getSchmeckles().
Fixes #989
```

More details in CONTRIBUTING.md

In your commit message, you put the *why* twice, but never the *what*

**Comment by dmarkowicz** [comment]
@greg0ire This is the most difficult part :smile: I changed according to the recommendations (I think so).

File: tests/Datagrid/ProxyQueryTest.php [hunk 1]
```diff
@@ -212,4 +214,30 @@ public function testSetHint()
...
+    public function testAddOrderedColumnsCompositeId()
+    {
+        $qb = $this->em->createQueryBuilder()
+                       ->select('IDENTITY(o.id1) as id1, IDENTITY(o.id2) as id2')
+                       ->distinct()
+                       ->from(self::COMPOSITE_ID_CLASS, 'o')
+                       ->orderBy('o.id1', 'ASC')
+                       ->addOrderBy('o.id2', 'ASC');
+
+        $pq = $this->getMockBuilder('Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery')
```
Comment (greg0ire) [inline tests/Datagrid/ProxyQueryTest.php]: Please use the `::class` notation everywhere you can

Comment (dmarkowicz) [reply tests/Datagrid/ProxyQueryTest.php]: @greg0ire ready for review

File: tests/Datagrid/ProxyQueryTest.php [hunk 2]
```diff
@@ -212,4 +214,30 @@ public function testSetHint()
...
+    public function testAddOrderedColumnsCompositeId()
+    {
+        $qb = $this->em->createQueryBuilder()
+                       ->select('IDENTITY(o.id1) as id1, IDENTITY(o.id2) as id2')
+                       ->distinct()
+                       ->from(CompositeIntIdEntity::class, 'o')
+                       ->orderBy('o.id1', 'ASC')
+                       ->addOrderBy('o.id2', 'ASC');
+
+        $pq = $this->getMockBuilder(ProxyQuery::class)
```
Comment (OskarStark) [inline tests/Datagrid/ProxyQueryTest.php]: please `createMock()` here

Comment (dmarkowicz) [reply tests/Datagrid/ProxyQueryTest.php]: @OskarStark Is that necessary? Support for < PHPUnit 5.4 was dropped in 456fb815935856fffcd4395acffdfdd93d89c6f4

File: tests/Datagrid/ProxyQueryTest.php [hunk 3]
```diff
@@ -212,4 +214,30 @@ public function testSetHint()
 
         $this->assertEquals(2, $result[0]['id']);
     }
+
+    public function testAddOrderedColumnsCompositeId()
+    {
+        $qb = $this->em->createQueryBuilder()
+                       ->select('IDENTITY(o.id1) as id1, IDENTITY(o.id2) as id2')
```
Comment (Soullivaneuh) [inline tests/Datagrid/ProxyQueryTest.php]: Bad indent,

File: src/Datagrid/ProxyQuery.php [hunk 4]
```diff
@@ -378,13 +380,17 @@ protected function getFixedQueryBuilder(QueryBuilder $queryBuilder)
         return $queryBuilder;
     }
 
-    private function addOrderedColumns(QueryBuilder $queryBuilder)
+    private function addOrderedColumns(QueryBuilder $queryBuilder, array $idSelects)
```
Comment (Soullivaneuh) [inline src/Datagrid/ProxyQuery.php]: Need a PHPDoc for `idSelects`

File: tests/Datagrid/ProxyQueryTest.php (hunk 2 above)
Comment (jordisala1991) [reply tests/Datagrid/ProxyQueryTest.php]: createMock is PHPUnit >= 5.4

**Comment by dmarkowicz** [comment]
Please review after last changes.

File: src/Datagrid/ProxyQuery.php (hunk 4 above)
Comment (dmarkowicz) [reply src/Datagrid/ProxyQuery.php]: @Soullivaneuh please review

File: tests/Datagrid/ProxyQueryTest.php (hunk 3 above)
Comment (dmarkowicz) [reply tests/Datagrid/ProxyQueryTest.php]: @Soullivaneuh please review

**Comment by OskarStark** [comment]
Thank you @dmarkowicz 👍
