### PR TITLE
Fix sorting by multiple columns in PostgreSQL and MySQL 5.7

### LINKED ISSUE #210: Error in multiple sorting (PosgreSQL)
I have a error in multiple sorting.

My code for create query:

``` php
    public function createQuery($context = 'list')
    {
        /** @var \Doctrine\ORM\EntityRepository $er */
        $er = $this->getConfigurationPool()->getContainer()
            ->get('doctrine')
            ->getRepository('FindCapacity\Entity\IndustryActivity');

        $qb = $er->createQueryBuilder('ia')
            ->orderBy('ia.root', 'ASC')
            ->addOrderBy('ia.lft', 'ASC')
        ;

        return new ProxyQuery($qb);
    }
}
```

Database: postgress 9.1.6

Error:

```
SQLSTATE[42P10]: Invalid column reference: 7 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

Solution this bug:
Reset "orderBy" dql part in countable and load `idx` queries.

Patchs:

``` patch
Index: vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/ProxyQuery.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/ProxyQuery.php   (revision )
+++ vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/ProxyQuery.php   (revision )
@@ -80,7 +80,7 @@

         // step 3 : retrieve the different subjects id
         $select = sprintf('%s.%s', $queryBuilderId->getRootAlias(), $idName);
-        $queryBuilderId->resetDQLPart('select');
+        $queryBuilderId->resetDQLParts(array('select', 'orderBy'));
         $queryBuilderId->add('select', 'DISTINCT ' . $select);

         //for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

``` patch
Index: vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/Pager.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/Pager.php    (revision )
+++ vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/Pager.php    (revision )
@@ -30,6 +30,7 @@
     public function computeNbResult()
     {
         $countQuery = clone $this->getQuery();
+        $countQuery->resetDQLPart('orderBy');

         if (count($this->getParameters()) > 0) {
             $countQuery->setParameters($this->getParameters());
```

Thank

### LINKED ISSUE #458: OrderBy with postgresql
I have a problem while trying to custom the createQuery in my admin class : 

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT c0_.id AS id0, c0_.id AS id1 FROM crm_product_goodplan c1_ INNER JOIN crm_product_product c0_ ON c1_.id = c0_.id LEFT JOIN crm_product_establishment c2_ ON c0_.establishment_id = c2_.id LEFT JOIN crm_product_agent c3_ ON c0_.advisor_id = c3_.id WHERE c0_.endProductionDate >= ? ORDER BY c0_.endProductionDate ASC, c0_.id ASC LIMIT 32 OFFSET 0' with params ["2015-06-02"]:

SQLSTATE[42P10]: Invalid column reference: 7 ERREUR: pour SELECT DISTINCT, ORDER BY, les expressions doivent apparaître dans la
liste SELECT
LINE 1: ...c3_.id WHERE c0_.endProductionDate >= $1 ORDER BY c0_.endPro...
^") in SonataAdminBundle:CRUD:base_list.html.twig at line 33.

this is my function : 

```
public function createQuery($context = 'list')
{
    $query = parent::createQuery($context);
    $today = new \DateTime(); 
    $query->andWhere('o.endProductionDate >= :today')->setParameter('today', $today->format('Y-m-d'))->orderBy('o.endProductionDate', 'ASC');

    return $query;
}
```

relating to the issue #210

### PR DESCRIPTION
**Pull request by dmarkowicz**
I am targeting this branch, because this is bug fix.

Closes #458, closes #210, closes #694, closes #703

## Changelog

```markdown
### Fixed
- Fix sorting by multiple columns in custom createQuery in PostgreSQL and MySQL 5.7
```
## Subject
This is continuation of #703. Multiple orderBy in custom createQuery causes errors.
PostgreSQL:
`SQLSTATE[42P10]: Invalid column reference: 7 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list `
MySQL 5.7 with ONLY_FULL_GROUP_BY mode (which is default):
`SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'mydb.c0_.mycolumn' which is not in SELECT list; this is incompatible with DISTINCT").`
I adapted solution proposed by @jerome-fix and added tests.

### CODE REVIEW

File: Datagrid/ProxyQuery.php [hunk 1]
```diff
@@ -309,24 +309,16 @@ protected function getFixedQueryBuilder(QueryBuilder $queryBuilder)
...
         */
-        // todo : check how doctrine behave, potential SQL injection here ...
-        if ($this->getSortBy()) {
-            $sortBy = $this->getSortBy();
-            if (strpos($sortBy, '.') === false) { // add the current alias
-                $sortBy = $rootAlias.'.'.$sortBy;
-            }
-            $sortBy .= ' AS __order_by';
-            $queryBuilderId->addSelect($sortBy);
-        }
```
Comment (dmarkowicz) [inline Datagrid/ProxyQuery.php]: Column from `getSortBy` is already added to `orderBy` list in `execute` and will be handled by `addOrderedColumns` below.

File: composer.json [hunk 2]
```diff
@@ -23,7 +23,7 @@
         "sonata-project/core-bundle": "^3.0",
         "sonata-project/exporter": "^1.3.1",
         "symfony/console": "^2.3 || ^3.0",
-        "symfony/doctrine-bridge": "^2.2 || ^3.0",
+        "symfony/doctrine-bridge": "^2.4 || ^3.0",
```
Comment (dmarkowicz) [inline composer.json]: Minimum 2.4 version is required for DoctrineTestHelper.

File: Datagrid/ProxyQuery.php [hunk 3]
```diff
@@ -355,4 +347,18 @@ protected function getFixedQueryBuilder(QueryBuilder $queryBuilder)
...
         return $queryBuilder;
     }
+
+    private function addOrderedColumns(QueryBuilder $queryBuilder)
+    {
+        /* For each ORDER BY clause defined directly in the DQL parts of the query,
+           we add an entry in the SELECT clause. */
+        $dqlParts = $queryBuilder->getDqlParts();
+        if ($dqlParts['orderBy'] && count($dqlParts['orderBy'])) {
+            foreach ($dqlParts['orderBy'] as $part) {
```
Comment (greg0ire) [inline Datagrid/ProxyQuery.php]: Could probably be simplified with a cast : https://3v4l.org/D6cRP

```php
<?php
$dqlParts = $queryBuilder->getDqlParts();
foreach ((array) $dqlParts['orderBy'] as $part) {
```

Comment (dmarkowicz) [reply Datagrid/ProxyQuery.php]: I like it, thanks.

**Comment by OskarStark** [comment]
Great job @dmarkowicz 🎉

**Comment by leonboot** [comment]
Seem MS SQL has similar issues, so you may want to add it to the list of servers in the changelog. I'm getting this error message when attempting to sort on multiple colums by overriding the `createQuery` method:

```
SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]ORDER BY items must appear in the select list if SELECT DISTINCT is specified.").
```

Seems very similar to the errors PostgreSQL and MySQL 5.7 are returning when trying to do a multi column sort.
