### PR TITLE
Fix computeNbResult in case of groupBy

### LINKED ISSUE #968: computeNbResult throw error when the query use a groupBy
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
sonata-project/admin-bundle              3.54.1 3.57.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.2 4.1.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.2 3.17.2 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.1.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.5.1  1.5.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.12.0 3.13.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
```

## Subject

When writing a custom filter like this
```
$queryBuilder->andHaving("SUM($contractSupportAlias.euroAmount) $operator :$parameterName");
$queryBuilder->groupBy($alias);
$queryBuilder->setParameter($parameterName, $value['value'] * 100);
```

Or like this
```
$queryBuilder->andHaving("MAX($relaunchAlias.creationDate) < :$parameterName");
$queryBuilder->groupBy($alias);
$queryBuilder->setParameter($parameterName, $date->format('Y-m-d H:i:s'));
```

Or again like this
```
$queryBuilder->andHaving("COUNT(DISTINCT $relaunchAlias) $operator :$parameterName");
$queryBuilder->groupBy($alias);
$queryBuilder->setParameter($parameterName, $value['value']);
```

With a `LEFT_JOIN` and a `GROUP BY`, we get an error
```
The query returned multiple rows. Change the query or use a different result function like getScalarResult().
```

It's coming from the `computeNbResult`.
```
public function computeNbResult()
{
    $countQuery = clone $this->getQuery();

    if (\count($this->getParameters()) > 0) {
        $countQuery->setParameters($this->getParameters());
    }

    $countQuery->select(sprintf(
        'count(%s %s.%s) as cnt',
        $countQuery instanceof ProxyQuery && !$countQuery->isDistinct() ? null : 'DISTINCT',
        current($countQuery->getRootAliases()),
        current($this->getCountColumn())
    ));

    return (int) ($countQuery->resetDQLPart('orderBy')->getQuery()->getOneOrNullResult(Query::HYDRATE_SINGLE_SCALAR));
}
```

I tried to `return 0` inside and my query works. The error is just coming from computeNbResult.

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject
Fix computeNbResult where groupBy was used

I am targeting this branch, because BC-break free.

Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/968

If this PR is merged, I would love a new release since we need this from our project.

## Changelog
```markdown
### Fixed
- Fix computeNbResult where groupBy was used
```

### CODE REVIEW

**Comment by greg0ire** [comment]
> I would love a new release since we need this from our project.

Really not an issue :)

**Comment by greg0ire** [comment]
Please sum up #968 in your commit message, and, also in your commit message, explain how your changes improve the situation. It is important to do that for all commits, but in this case I think it is crucial, because this fix might cause unforeseen issues.

File: src/Datagrid/Pager.php [hunk 1]
```diff
@@ -45,7 +45,10 @@ public function computeNbResult()
             current($this->getCountColumn())
         ));
 
-        return (int) ($countQuery->resetDQLPart('orderBy')->getQuery()->getOneOrNullResult(Query::HYDRATE_SINGLE_SCALAR));
+        return array_sum(array_column(
+            ($countQuery->resetDQLPart('orderBy')->getQuery()->getResult(Query::HYDRATE_SCALAR)),
```
Comment (greg0ire) [inline src/Datagrid/Pager.php]:
```suggestion
            $countQuery->resetDQLPart('orderBy')->getQuery()->getResult(Query::HYDRATE_SCALAR),
```

**Comment by VincentLanglet** [comment]
@greg0ire Is my commit better ? It's not clear for me what I should add in it.
It's still possible to find the PR and the issue from the commit.

**Comment by greg0ire** [comment]
It's better in that I understand better what the issue is about. I'm going to try to improve it and force push.

**Review by greg0ire — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you 😃

**Comment by greg0ire** [comment]
As promised: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/releases/tag/3.14.0

**Comment by VincentLanglet** [comment]
Thanks a lot
