### PR TITLE
Use "BINARY()" DQL function for case sensitive MySQL pattern matching in `StringFilter::filter()`

### LINKED ISSUE #1387: Filter option "case_sensitive" is not being respected with MySQL
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.95.0 3.95.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.22.0 4.5.3  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.1.1  Cache library
sonata-project/datagrid-bundle           3.3.0  3.3.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.11.0 1.12.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.32.0 3.32.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/entity-audit-bundle       1.1.0  1.2.0  Audit for Doctrine Entities
sonata-project/exporter                  2.5.0  2.6.1  Lightweight Exporter library
sonata-project/form-extensions           1.8.1  1.9.0  Symfony form extensions
sonata-project/intl-bundle               2.10.0 2.10.1 Symfony SonataIntlBundle
sonata-project/media-bundle              3.29.0 3.31.0 Symfony SonataMediaBundle
sonata-project/twig-extensions           1.5.0  1.5.1  Sonata twig extensions
sonata-project/user-bundle               4.10.1 4.11.1 Symfony SonataUserBundle
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amazon-sqs-messenger       v5.2.2  v5.2.4  Symfony Amazon SQS extension Messenger Bridge
symfony/amqp-messenger             v5.2.2  v5.2.4  Symfony AMQP extension Messenger Bridge
symfony/asset                      v4.4.19 v5.2.4  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v5.2.2  v5.2.4  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v5.2.2  v5.2.6  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                     v4.4.19 v5.2.4  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v4.4.19 v5.2.6  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.2.2  v5.2.4  Converts CSS selectors to XPath expressions
symfony/debug                      v4.4.19 v4.4.20 Provides tools to ease debugging PHP code
symfony/debug-bundle               v5.1.11 v5.2.4  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/debug-pack                 v1.0.9  v1.0.9  A debug pack for Symfony projects
symfony/dependency-injection       v4.4.19 v5.2.6  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.19 v5.2.6  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.2.2  v5.2.5  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.2.2  v5.2.4  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.2.2  v5.2.4  Registers environment variables from a .env file
symfony/error-handler              v4.4.19 v5.2.6  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v4.4.19 v5.2.4  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v1.1.9  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.2.2  v5.2.4  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v4.4.19 v5.2.6  Provides basic utilities for the filesystem
symfony/finder                     v4.4.19 v5.2.4  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.11.0 v1.12.2 Composer plugin for Symfony
symfony/form                       v4.4.19 v5.2.6  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.19 v5.2.6  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.2.2  v5.2.6  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.3.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.19 v5.2.4  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v4.4.19 v5.2.6  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.2.2  v5.2.4  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v5.2.2  v5.2.6  Helps sending emails
symfony/maker-bundle               v1.28.0 v1.30.2 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.2.2  v5.2.5  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.2.2  v5.2.6  Allows manipulating MIME messages
symfony/monolog-bridge             v5.2.2  v5.2.5  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.6.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v5.2.2  v5.2.4  Provides an improved replacement for the array_replace PHP function
symfony/phpunit-bridge             v5.2.2  v5.2.6  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-php80             v1.22.0 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.19 v5.2.4  Executes commands in sub-processes
symfony/profiler-pack              v1.0.5  v1.0.5  A pack for the Symfony web profiler
symfony/property-access            v5.2.2  v5.2.4  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.2.2  v5.2.4  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v4.4.18 v5.2.4  Symfony ProxyManager Bridge
symfony/redis-messenger            v5.2.2  v5.2.4  Symfony Redis extension Messenger Bridge
symfony/requirements-checker       v1.1.8  v2.0.0  Check Symfony requirements and give recommendations
symfony/routing                    v4.4.19 v5.2.6  Maps an HTTP request to a set of configuration variables
symfony/security                   v4.4.19 v4.4.21 Provides a complete security system for your web application
symfony/security-acl               v3.1.1  v3.1.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.19 v5.2.6  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/serializer                 v5.2.2  v5.2.4  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.2.2  v5.2.4  Provides a way to profile code
symfony/string                     v5.2.2  v5.2.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/swiftmailer-bundle         v3.5.2  v3.5.2  Symfony SwiftmailerBundle
symfony/templating                 v4.4.19 v5.2.4  Provides all the tools needed to build any kind of template system
symfony/translation                v4.4.19 v5.2.6  Provides tools to internationalize your application
symfony/translation-contracts      v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.19 v5.2.6  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v4.4.19 v5.2.4  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v4.4.19 v5.2.6  Provides tools to validate values
symfony/var-dumper                 v5.2.2  v5.2.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.2.2  v5.2.4  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v5.0.11 v5.2.6  Symfony WebProfilerBundle
symfony/web-server-bundle          v4.4.19 v4.4.21 Provides commands for running applications using the PHP built-in web server
symfony/webpack-encore-bundle      v1.9.0  v1.11.1 Integration with your Symfony app & Webpack Encore!
symfony/workflow                   v5.2.2  v5.2.4  Provides tools for managing a workflow or finite state machine
symfony/yaml                       v4.4.19 v5.2.5  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

<details><summary>show</summary>
<p>

```
$ php -v
PHP 7.3.24 (cli) (built: Nov 18 2020 09:59:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.24, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.46.4~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

</p>
</details>

## Subject

Filter option "case_sensitive" is not being respected with MySQL.
IMO, we should find a way to detect the connection type and provide the required modifications to the query in order to get this option honored when its value is `true`.

See:
* https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html
* https://stackoverflow.com/questions/8083455/like-case-sensitive-in-mysql

Related to #870.

## Steps to reproduce
Use the option `'case_sensitive' => true` in a string filter within a MySQL connection.

## Expected results
No results when a string in the database is not using the same casing that the filter term.

## Actual results
The filter matches with terms using different casing. IE "Term" matches "term".

### PR DESCRIPTION
**Pull request by phansys**
## Subject
Use "BINARY()" DQL function for case sensitive MySQL pattern matching in `StringFilter::filter()`.

I am targeting this branch, because these changes respect BC.

Closes #1387.

## Changelog

```markdown
### Added
- Call to `BINARY()` (`DoctrineExtensions\Query\Mysql\Binary`) DQL function for MySQL pattern matching when it is available and "case_sensitive" option is set to `true` in `StringFilter::filter()`.

### Changed
- Default value for the "case_sensitive" option from `true` to `null` in `StringFilter`.

### Fixed
- Respecting "case_sensitive" when it is set to `true` along MySQL columns using other collations than "utf8mb4_0900_as_cs" or "utf8mb4_bin".

### Deprecated
- Omitting or not passing an instance of `Doctrine\ORM\EntityManagerInterface` as argument 1 to `StringFilter::__construct()`.
```

## To do

- [x] Update the tests;
- [x] Update the documentation;
- [x] Add an upgrade note;
- [x] Determine if we must deprecate something;
- [x] Check if we can / should configure the DQL function automatically.

### CODE REVIEW

File: src/Filter/StringFilter.php [hunk 1]
```diff
@@ -87,14 +100,21 @@ public function filter(BaseProxyQueryInterface $query, $alias, $field, $data)
...
         $parameterName = $this->getNewParameterName($query);
 
-        $or = $query->getQueryBuilder()->expr()->orX();
+        $caseSensitive = $this->getOption('case_sensitive');
 
-        if ($this->getOption('case_sensitive')) {
-            $or->add(sprintf('%s.%s %s :%s', $alias, $field, $operator, $parameterName));
+        if (false === $caseSensitive) {
+            $clause = 'LOWER(%s.%s) %s :%s';
+        } elseif (true === $caseSensitive && null !== $this->doctrineConfig && Binary::class === $this->doctrineConfig->getCustomStringFunction('binary')) {
```
Comment (core23) [inline src/Filter/StringFilter.php:107]: Will this work if you don't have `beberlei/doctrineextensions` installed? I would expect some kind of exception.

Comment (phansys) [reply src/Filter/StringFilter.php:107]: The condition will work, it returns false in that case, allowing the execution flow to reach the body of the `else` condition.

File: src/Filter/StringFilter.php [hunk 2]
```diff
@@ -47,6 +50,16 @@ class StringFilter extends Filter
         StringOperatorType::TYPE_NOT_CONTAINS,
     ];
 
+    /**
+     * @var Configuration|null
+     */
+    private $doctrineConfig;
+
+    public function __construct(?EntityManagerInterface $em = null)
```
Comment (VincentLanglet) [inline src/Filter/StringFilter.php:58]: Do we have to add a NEXT_MAJOR comment to make this mandatory ?

**Comment by phansys** [comment]
I wonder if we should deprecate the `null` value in the "case_sensitive" option.

**Comment by phansys** [comment]
>I was thinking that the null value would be the default one in order to avoid a change in the current behavior.

Do you suggest to change the default value at `getDefaultOptions()`?
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/5ba9ff8ec5130d12855be751d393445a1dbc258e/src/Filter/StringFilter.php#L173-L178

>If we want to deprecate the null value, I would recommend to introduce a global option configuration.

I'm fine with any of these options.

**Comment by VincentLanglet** [comment]
> > I was thinking that the null value would be the default one in order to avoid a change in the current behavior.
> 
> Do you suggest to change the default value at `getDefaultOptions()`?

Yes,
- If a developer wasn't passing any option, it won't change the behavior
- If a developer was passing false, it won't change the behavior
- If a developer was passing true, it can be considered as a patch

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Tests on different platform were failing, I try to restart them

**Comment by phansys** [comment]
As a future improvement, I think we could analyze the possibility of detect the availability of the `DoctrineExtensions\Query\Mysql\Binary` DQL extension regardless its name (currently it must be named "binary").
I don't know if it is feasible in a compiler pass.

File: docs/reference/filter_field_definition.rst [hunk 3]
```diff
@@ -73,10 +73,18 @@ StringFilter
...
-* ``case_sensitive`` - set to ``false`` to make the search case insensitive. By default ``true`` is used;
+* ``case_sensitive`` - set to ``false`` to make the search case insensitive. By default ``null`` is used;
 * ``trim`` - use one of ``Sonata\DoctrineORMAdminBundle\Filter\TRIM_*`` constants to control the clearing of blank spaces around in the value. By default ``Sonata\DoctrineORMAdminBundle\Filter\TRIM_BOTH`` is used;
 * ``allow_empty`` - set to ``true`` to enable search by empty value. By default ``false`` is used.
 
+.. versionadded:: 3.x
+
+    In order to perform real case sensitive comparisons along the MySQL platform, the ``BINARY()`` function
+    will be used when "case_sensitive" option is set to ``true`` and the `DoctrineExtensions\Query\Mysql\Binary <https://github.com/beberlei/DoctrineExtensions#doctrineextensions>`_
+    DQL extension is registered using the name "binary". This behavior requires the package "beberlei/doctrineextensions".
```
Comment (VincentLanglet) [inline docs/reference/filter_field_definition.rst:84]: Do you know if it's case-sensitive or 
```
string_functions:
                BINARY: DoctrineExtensions\Query\Mysql\Binary
```
works too ?

Comment (phansys) [reply docs/reference/filter_field_definition.rst:84]: Yes, `Doctrine\ORM\Configuration::getCustomStringFunction()` calls `strtolower()`.

File: src/Filter/StringFilter.php [hunk 4]
```diff
@@ -129,7 +165,7 @@ public function filter(BaseProxyQueryInterface $query, $alias, $field, $data)
             $parameterName,
             sprintf(
                 $format,
-                $this->getOption('case_sensitive') ? $data['value'] : mb_strtolower($data['value'])
+                $caseSensitive || '' === $data['value'] ? $data['value'] : mb_strtolower($data['value'])
```
Comment (franmomu) [inline src/Filter/StringFilter.php:168]: I haven't checked the failure, but could be because of changing `case_sensitive` to `null` by default, so here it's executed the `mb_strtolower($data['value'])` part and in `PostgreSQL` would not perform the case sensitive query.

Comment (VincentLanglet) [reply src/Filter/StringFilter.php:168]: could change to `false !== $caseSensitive`

**Comment by franmomu** [comment]
Since it should be quite easy to add a functional test, can we add one? just to see it working, I don't mind creating it in your branch if you want to.

For example in `AuthorAdmin` there are two filters, we could make one case sensitive and the other one not.

**Review by VincentLanglet — DISMISSED** [review]

File: tests/Filter/StringFilterTest.php [hunk 5]
```diff
@@ -34,50 +48,133 @@ public function testEmpty(): void
...
+        ];
+    }
+
     /**
      * @dataProvider getValues
      */
     public function testContains($value, bool $allowEmpty): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:167]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

I think this should be mock since the method `with()` is called and is not present in [`InvocationStubber`](https://github.com/sebastianbergmann/phpunit/blob/1b3675760e1a6d3048b53eb092022a67951beaa4/src/Framework/MockObject/Builder/InvocationStubber.php).

File: tests/Filter/StringFilterTest.php [hunk 6]
```diff
@@ -100,7 +197,17 @@ public function testContains($value, bool $allowEmpty): void
      */
     public function testStartsWith($value, bool $allowEmpty): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:200]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/StringFilterTest.php [hunk 7]
```diff
@@ -123,7 +230,17 @@ public function testStartsWith($value, bool $allowEmpty): void
      */
     public function testEndsWith($value, bool $allowEmpty): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:233]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/StringFilterTest.php [hunk 8]
```diff
@@ -146,7 +263,17 @@ public function testEndsWith($value, bool $allowEmpty): void
      */
     public function testNotContains($value, bool $allowEmpty): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:266]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/StringFilterTest.php [hunk 9]
```diff
@@ -169,7 +296,17 @@ public function testNotContains($value, bool $allowEmpty): void
      */
     public function testEquals($value, bool $allowEmpty): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:299]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/StringFilterTest.php [hunk 10]
```diff
@@ -192,7 +329,17 @@ public function testEquals($value, bool $allowEmpty): void
      */
     public function testNotEquals($value, bool $allowEmpty): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:332]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/StringFilterTest.php [hunk 11]
```diff
@@ -212,7 +359,17 @@ public function testNotEquals($value, bool $allowEmpty): void
 
     public function testEqualsWithValidParentAssociationMappings(): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:362]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/StringFilterTest.php [hunk 12]
```diff
@@ -287,7 +463,17 @@ public function caseSensitiveDataProvider(): array
      */
     public function testFormatOption(): void
     {
-        $filter = new StringFilter();
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (franmomu) [inline tests/Filter/StringFilterTest.php:466]:
```suggestion
        $doctrineConfig = $this->createMock(Configuration::class);
```

File: tests/Filter/FilterTest.php [hunk 13]
```diff
@@ -117,12 +117,21 @@ public function testOrExpression(string $expected, array $filterOptionsCollectio
 
     public function orExpressionProvider(): iterable
     {
+        $doctrineConfig = $this->createStub(Configuration::class);
```
Comment (VincentLanglet) [inline tests/Filter/FilterTest.php:120]: createMock.

`with` doesn't exist for stubs.

Comment (phansys) [reply tests/Filter/FilterTest.php]: Done.

**Review by VincentLanglet — APPROVED** [review]

**Review by franmomu — APPROVED** [review]
