### PR TITLE
Prevent trim function to be executed with null value on StringFilter

### LINKED ISSUE #900: Type error: trim() expects parameter 1 to be string, null given - String Filter
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.45.1 3.45.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0 3.14.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.15.0 3.16.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.1  3.8.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.0 1.11.0 Lightweight Exporter library
sonata-project/google-authenticator      2.2.0  2.2.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.5.0  2.5.0  Symfony SonataIntlBundle
sonata-project/user-bundle               3.6.0  4.3.0  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2  Integrates Assetic into Symfony2
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
symfony/monolog-bundle     v3.3.1  v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.49 v4.2.3  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.10.0 v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv     v1.10.0 v1.10.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.10.0 v1.10.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.5  Symfony SwiftmailerBundle
symfony/symfony            v2.8.49 v3.4.22 The Symfony PHP framework
symfony/workflow           v3.4.21 v3.4.22 Symfony Workflow Component
```

#### PHP version

```
$ php -v
PHP 7.2.15-0ubuntu0.18.10.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-0ubuntu0.18.10.1, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

First of all, I know I'm using a old Symfony version, but upgrading this project right now is complicated. I overrided a lot of files but I can't find out why this is happening.

The StringFilter is receiving null instead of a string. I haven't managed to debug it yet, to find out which admin or field is firing the error (this bug only happens in production environment, can't manage to reproduce it on dev). 

But I know that to fix I can simply add a check if `$data['value'] === null` on this [line](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Filter/StringFilter.php#L23). But I don't know if this bug is exclusive on my project.

That being said, should I open a PR for this? It's a BC change. So I don't think it has a problem. I just wanted to check.

### PR DESCRIPTION
**Pull request by ejkun**
## Subject
Since the project is now using strict_types send null value to the trim function would cause an exception. To fix that a check for null value inside  was added.

I am targeting this branch, because the strict types are not being used in 2.x.

Closes #900

## Changelog

```markdown
### Added
- Added check for null value to prevent exception on StringFilter
```

### CODE REVIEW

**Comment by OskarStark** [comment]
Could you add a testcase?

**Comment by ejkun** [comment]
Yes, should I make it in a different commit? Or rebase the project?

**Comment by ejkun** [comment]
It's already been tested [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/tests/Filter/StringFilterTest.php#L30)

**Comment by ejkun** [comment]
My mistake, the test does not check an active filter with a null value. I will add the test case.

File: tests/Filter/StringFilterTest.php [hunk 1]
```diff
@@ -34,6 +34,18 @@ public function testEmpty()
         $this->assertFalse($filter->isActive());
     }
 
+    public function testNullValue()
```
Comment (ejkun) [inline tests/Filter/StringFilterTest.php]: Added testCase.

When the filter is passed with a null value it should be inactive.

**Comment by OskarStark** [comment]
Thank you 👍

**Comment by greg0ire** [comment]
Thanks @ejkun !
