### PR TITLE
Fix FieldDescription for multi-level embedded properties

### LINKED ISSUE #826: Can not use multi-level embedded properties
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.33.0 3.34.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.4.2  3.5.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminB...
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
```
Notice: Error reporoduced on latest build.

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2 v2.8.2 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.2 v3.2.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.4 v4.0.8 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.2.2 Symfony SwiftmailerBundle
symfony/symfony            v3.4.4 v3.4.8 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.2.4 (cli) (built: Apr  5 2018 00:37:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

Can not use multi-level embedded properties.
Example: ebedded_first.ebedded_second.field

Maybe bug in this code:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Model/ModelManager.php#L102-L109
Impossible to obtain metadata from embedded class in doctrine.

## Steps to reproduce

For example entity with map bounds and coordinates.

First embedded class
```
/**
 * Class Bounds
 * @ORM\Embeddable()
 */
class Bounds implements ComparableInterface
{
    /**
     * @ORM\Embedded(class="Coordinates", columnPrefix="sw_")
     * @var Coordinates
     */
    private $southwest;

    /**
     * @return Coordinates
     */
    public function getSouthwest(): Coordinates
    {
        if (!$this->southwest) {
            $this->setSouthwest(new Coordinates());
        }

        return $this->southwest;
    }

    /**
     * @param Coordinates $southwest
     * @return Bounds
     */
    public function setSouthwest(?Coordinates $southwest): Bounds
    {
        $this->southwest = $southwest;
        return $this;
    }
}
```

Second embedded class
```
/**
 * Class Coordinates
 * @ORM\Embeddable()
 */
class Coordinates implements ComparableInterface
{
    /**
     * @ORM\Column(type="decimal", precision=9, scale=5, nullable=true)
     */
    private $lat;

    /**
     * @return string|null
     */
    public function getLat(): ?string
    {
        return $this->lat;
    }

    /**
     * @param string $lat
     * @return Coordinates
     */
    public function setLat(?string $lat)
    {
        $this->lat = $lat;
        return $this;
    }
}
```

Entity
```
/**
 * Class Point
 * @ORM\Entity()
 */
class Point
{
    /**
     * @ORM\Embedded(class="Bounds", columnPrefix="bounds_")
     * @var Bounds
     */
    private $bounds;

    /**
     * @return Bounds
     */
    public function getBounds(): ?Bounds
    {
        return $this->bounds;
    }

    /**
     * @param Bounds $bounds
     * @return $this
     */
    public function setBounds(?Bounds $bounds)
    {
        $this->bounds = $bounds;
        return $this;
    }
}
```

## Actual results

On edit form:

```
RuntimeException:
No entity manager defined for class ***\***Bundle\Entity\Geo\Bounds

  at vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:287
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getEntityManager('***\\***Bundle\\Entity\\Geo\\Bounds')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:63)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getMetadata('***\\***Bundle\\Entity\\Geo\\Bounds')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:90)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getParentMetadataForProperty('***\\***Bundle\\Entity\\Hotel\\Hotel', 'bounds.southwest.lat')
     (vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php:143)
  at Sonata\DoctrineORMAdminBundle\Model\ModelManager->getNewFieldDescriptionInstance('***\\***Bundle\\Entity\\Hotel\\Hotel', 'bounds.southwest.lat', array('type' => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\NumberType', 'route' => array('name' => 'edit', 'parameters' => array())))
     (vendor/sonata-project/admin-bundle/src/Form/FormMapper.php:101)
  at Sonata\AdminBundle\Form\FormMapper->add('bounds.southwest.lat', 'Symfony\\Component\\Form\\Extension\\Core\\Type\\NumberType', array('label' => 'Southwest latitude', 'scale' => 5, 'constraints' => array(object(Range)), 'property_path' => 'bounds.southwest.lat'))
     (src/Apl/HotelsDbBundle/Admin/AbstractHotelsDbAdmin.php:66)
  at ***\***Bundle\Admin\AbstractHotelsDbAdmin->addCoordinatesField(object(FormMapper), 'bounds.southwest', array('label' => 'Southwest latitude'), array('label' => 'Southwest longitude'))
     (src/Apl/HotelsDbBundle/Admin/Hotel/HotelAdmin.php:49)
  at ***\***Bundle\Admin\Hotel\HotelAdmin->configureFormFields(object(FormMapper))
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:1188)
  at Sonata\AdminBundle\Admin\AbstractAdmin->defineFormBuilder(object(FormBuilder))
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:1175)
  at Sonata\AdminBundle\Admin\AbstractAdmin->getFormBuilder()
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:2842)
  at Sonata\AdminBundle\Admin\AbstractAdmin->buildForm()
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:1232)
  at Sonata\AdminBundle\Admin\AbstractAdmin->getForm()
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:312)
  at Sonata\AdminBundle\Controller\CRUDController->editAction('1')
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:32)
```

I'm trying to do something stupid? :)

### PR DESCRIPTION
**Pull request by aurelien-vtech**
I am targeting this branch, because it's BC bug fix..

Closes #826 

## Changelog

```markdown
### Fixed
- Fix FieldDescription for multi-level embedded properties
```

## To do
- [x] Update the tests

### CODE REVIEW

**Comment by aurelien-vtech** [comment]
Tests updated

File: tests/Fixtures/Entity/Embeddable/SubEmbeddedEntity.php [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+namespace Sonata\DoctrineORMAdminBundle\Tests\Fixtures\Entity\Embeddable;
+
+class SubEmbeddedEntity
+{
+    /**
+     * @var bool
+     */
+    protected $plainField;
+}
```
Comment (kunicmarko20) [inline tests/Fixtures/Entity/Embeddable/SubEmbeddedEntity.php]: Please configure your IDE to always add a newline at end of file, this will make the red pictogram disappear.

File: tests/Model/ModelManagerTest.php [hunk 2]
```diff
@@ -249,6 +250,10 @@ public function testGetParentMetadataForProperty()
         list($metadata, $lastPropertyName) = $modelManager
             ->getParentMetadataForProperty($containerEntityClass, 'associatedEntity.embeddedEntity.plainField');
         $this->assertEquals($metadata->fieldMappings[$lastPropertyName]['type'], 'boolean');
+
+        list($metadata, $lastPropertyName) = $modelManager
+            ->getParentMetadataForProperty($containerEntityClass, 'associatedEntity.embeddedEntity.subEmbeddedEntity.plainField');
```
Comment (kunicmarko20) [inline tests/Model/ModelManagerTest.php]: Can you break this one more time? We follow PSR-2 and your line shouldn't be longer than 120 chars

File: tests/Fixtures/Entity/Embeddable/SubEmbeddedEntity.php (hunk 1 above)
Comment (aurelien-vtech) [reply tests/Fixtures/Entity/Embeddable/SubEmbeddedEntity.php]: Should be OK

File: tests/Model/ModelManagerTest.php (hunk 2 above)
Comment (aurelien-vtech) [reply tests/Model/ModelManagerTest.php]: Done

**Comment by greg0ire** [comment]
From [the docs](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html):

> Embeddables can only contain properties with basic @Column mapping.

**Comment by Bonfante** [comment]
@greg0ire 
when looking to doctrine repo I can't find any doc supporting nested embeddables, but in there is a lot of PR to this behevour https://github.com/doctrine/doctrine2/pull/1309
I get similir issue with nested embeddables in the list. Would be greate to add this functionality.
But maybe is a good idea to change ModelManager::getMetadata too.
It was the first solution I found, but it still has issues with ['editable' => true] in configureListFields.
`
/**
     * @param string $class
     *
     * @return ClassMetadata
     * @throws \RuntimeException
     * @throws \ReflectionException
     * @throws \Doctrine\Common\Persistence\Mapping\MappingException
     */
    public function getMetadata($class)
    {
        try {
            return $this->getEntityManager($class)->getMetadataFactory()->getMetadataFor($class);
        } catch (\RuntimeException $exception) {
            $metadata = $this->registry->getEntityManager()->getMetadataFactory()->getMetadataFor($class);
            if ($metadata->isEmbeddedClass) {
                return $metadata;
            }
            throw new \RuntimeException(sprintf('Failed to get metadata for class %s', $class),$exception);;
        }
    }

`

**Comment by greg0ire** [comment]
Looking at https://github.com/doctrine/doctrine2/pull/1311, it seems indeed to be somewhat supported

**Comment by OskarStark** [comment]
Nice simplicifaction 👍
