### PR TITLE
fixes #672 build actions field description based on provided type too

### LINKED ISSUE #672: Cannot add a column of type "actions" (or is it "action"?) which is not named "_action" in the list view
#### Sonata packages

```
sonata-project/admin-bundle              3.15.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4 Symfony SwiftmailerBundle
symfony/symfony            v3.2.6 The Symfony PHP framework
```

#### PHP version

```
PHP 7.1.2 (cli) (built: Feb 17 2017 10:52:17) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

Cannot add a column of type `actions` (or is it `action`?) which is not named `_action` in the list view.

`ListBuilder` build all the required properties only for the field named `_action`.

The [documentation](https://symfony.com/doc/current/bundles/SonataAdminBundle/reference/action_list.html) says the field type for a custom action field is `actions`, the code in `ListBuilder` assigns the type `action` but ignores it anyway.

## Steps to reproduce

```php
class FooAdmin extends AbstractAdmin
{
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('something', 'actions', [
                'actions' => [
                    'show' => [],
                ],
            ]);
}
```

Same result with type parameter being `action`.

## Expected results

```html
<!-- START
    fieldName: something
    template: SonataAdminBundle:CRUD:list__action.html.twig
    compiled template: SonataAdminBundle:CRUD:list__action.html.twig
    -->
```

## Actual results

```html
<!-- START
    fieldName: something
    template: SonataAdminBundle:CRUD:base_list_field.html.twig
    compiled template: SonataAdminBundle:CRUD:base_list_field.html.twig
    -->
```

## Current workaround

Full configuration of templates including for each action, otherwise an error will be thrown.

```php
class FooAdmin extends AbstractAdmin
{
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('something', 'actions', [
                'template' => 'SonataAdminBundle:CRUD:list__action.html.twig',
                'actions' => [
                    'show' => [
                        'template' => 'SonataAdminBundle:CRUD:list__action_show.html.twig',
                    ],
                ],
            ]);
}
```

## Proposed fix

In `\Sonata\DoctrineORMAdminBundle\Builder\ListBuilder::fixFieldDescription` method:

Before:
```php
if ($fieldDescription->getName() == '_action') {
    $this->buildActionFieldDescription($fieldDescription);
}
```

After:
```php
if ($fieldDescription->getName() === '_action' || $fieldDescription->getType() === 'actions') {
    $this->buildActionFieldDescription($fieldDescription);
}
```

Probably not too far from a pull request.

### PR DESCRIPTION
**Pull request by andrewmy**
I am targeting this branch, because it's a patch.

Closes #672

## Changelog

```markdown
### Fixed
- A list field with `actions` type will get all the required field options just like the `_action` field.
- `_action` field will get a proper `actions` type.
```
## Subject

`ListBuilder` fix.

### CODE REVIEW

**Comment by greg0ire** [comment]
> - `_action` field will get a proper `actions` type, not that has any impact.

Then it should not appear in the changelog

File: Tests/Builder/ListBuilderTest.php [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+        $this->listBuilder = new ListBuilder($this->typeGuesser);
+        $this->admin = $this
+            ->getMockBuilder('Sonata\AdminBundle\Admin\AbstractAdmin')
+            ->disableOriginalConstructor()->getMock();
+        $this->modelManager = $this
+            ->createMock('Sonata\DoctrineORMAdminBundle\Model\ModelManager');
+        $this->modelManager->expects($this->once())
+            ->method('hasMetadata')->willReturn(false);
+        $this->admin->expects($this->atLeastOnce())
+            ->method('getModelManager')->willReturn($this->modelManager);
```
Comment (greg0ire) [inline Tests/Builder/ListBuilderTest.php]: Please consider using Prophecy here.

File: Tests/Builder/ListBuilderTest.php [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+    public function testAddListActionField()
+    {
+        $fieldDescription = new FieldDescription();
+        $fieldDescription->setName('foo');
+        $list = $this->listBuilder->getBaseList();
+        $this->listBuilder
+            ->addField($list, 'actions', $fieldDescription, $this->admin);
+
+        $this->assertEquals(
```
Comment (greg0ire) [inline Tests/Builder/ListBuilderTest.php]: Please always favor `assertSame` over `assertEquals`

Comment (andrewmy) [inline Tests/Builder/ListBuilderTest.php]: OK

File: Tests/Builder/ListBuilderTest.php (hunk 1 above)
Comment (andrewmy) [inline Tests/Builder/ListBuilderTest.php]: Prophecy required a couple more method definitions, alright.

File: Tests/Builder/ListBuilderTest.php [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+
+    /**
+     * @var ListBuilder
+     */
+    protected $listBuilder;
+
+    /**
+     * @var AdminInterface|\PHPUnit_Framework_MockObject_MockObject
+     */
+    protected $admin;
```
Comment (greg0ire) [inline Tests/Builder/ListBuilderTest.php]: If you make the class `final`, then you should probably use `private` too. Note that we don't make test class final usually, because they are not considered part of our public API.

Comment (andrewmy) [inline Tests/Builder/ListBuilderTest.php]: Copied the test class definition from other tests int he same dir, will remove `final`.
Btw, Mocks instead of Prophecy were used because of the same reason.

**Comment by andrewmy** [comment]
> Then it should not appear in the changelog

Well, the impact is more correct builder output so that it could be relied on. My comment was about the real world impact which I didn't see yet.

**Comment by greg0ire** [comment]
> Well, the impact is more correct builder output so that it could be relied on. My comment was about the real world impact which I didn't see yet.

The CHANGELOG is directed at end users of the bundle, so try to make it as concise and clear as possible

File: Tests/Builder/ListBuilderTest.php [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+
+    /**
+     * @var ModelManager|\Prophecy\Prophecy\ObjectProphecy
+     */
+    protected $modelManager;
+
+    protected function setUp()
+    {
+        $prophet = new Prophet();
```
Comment (jordisala1991) [inline Tests/Builder/ListBuilderTest.php]: No need to create a `prophet`, you can use `$this->prophesize('classname');`

File: Tests/Builder/ListBuilderTest.php [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+
+        $this->typeGuesser = $prophet->prophesize(
+            'Sonata\AdminBundle\Guesser\TypeGuesserInterface'
```
Comment (jordisala1991) [inline Tests/Builder/ListBuilderTest.php]: No need to linebreak this, is not under 80/100/120 chars right? (this applies for the other linebreaks)

**Comment by jordisala1991** [comment]
This change needs to be done on all the others database bundles (PHPCR, mongodb and propel)?

File: Tests/Builder/ListBuilderTest.php (hunk 4 above)
Comment (andrewmy) [inline Tests/Builder/ListBuilderTest.php]: Thanks, didn't know it was available.

File: Tests/Builder/ListBuilderTest.php (hunk 5 above)
Comment (andrewmy) [inline Tests/Builder/ListBuilderTest.php]: I was aiming at under 85 chars. Replaced strings with `*::class`, they're `use`d anyway.

Comment (andrewmy) [inline Tests/Builder/ListBuilderTest.php]: StyleCI isn't happy about this, reverting :|

**Comment by jordisala1991** [comment]
Can you squash your commits into one or two with a meaninful message?

**Comment by OskarStark** [comment]
is this BC @greg0ire ?

**Comment by OskarStark** [comment]
> This change needs to be done on all the others database bundles (PHPCR, mongodb and propel)?

What about this? @jordisala1991 ?

**Comment by greg0ire** [comment]
> is this BC @greg0ire ?

What part do you have doubts about?

File: Builder/ListBuilder.php [hunk 6]
```diff
@@ -164,7 +164,7 @@ public function buildActionFieldDescription(FieldDescriptionInterface $fieldDesc
         }
 
         if (null === $fieldDescription->getType()) {
-            $fieldDescription->setType('action');
+            $fieldDescription->setType('actions');
```
Comment (OskarStark) [inline Builder/ListBuilder.php]: this on @greg0ire, could this be handled in userland in a different way?

Comment (greg0ire) [inline Builder/ListBuilder.php]: Oh right… I'm not sure what this is used for ? Maybe for deciding which template to use? @andrewmy do you know what the implications of changing this are?

Comment (andrewmy) [inline Builder/ListBuilder.php]: Currently (before this PR) the bundle ignores both the `action`/`actions` types — the code chooses the template only for the `_action`-named field, and this is the essence of the bug being fixed.

Absence of any other standard action fields makes me conclude that there are no implications inside the bundle. Judging by absence of registered issues, end users don't rely on `action` or `actions` type too, so no implications there too.

This line makes the change consistent — it would be confusing to require end suers to set the type to `actions` and mention but not even use `action` internally.

Comment (greg0ire) [inline Builder/ListBuilder.php]: Thanks a lot for the due diligence @andrewmy , it makes this feel way safer to merge!

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/Builder/ListBuilder.php#L150

https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/Builder/ListBuilder.php#L76

This is for the SonataDoctrineMongoDBAdminBundle, and it will be the same on the other persistence layers.

@andrewmy can you help with those also after this PR gets merged? It would be nice :)

**Comment by jordisala1991** [comment]
Is this PR missing something or do I merge it?

**Comment by greg0ire** [comment]
Merge it please

**Comment by jordisala1991** [comment]
Thanks @andrewmy

**Comment by andrewmy** [comment]
Will try this with sister bundles later this week.
