### PR TITLE
throw MissingPropertyMetadataException if propertyName could not be found in mappings

### LINKED ISSUE #695: configureDatagridFilters doesn't recognize fields from a trait
Original issue : [https://github.com/sonata-project/SonataAdminBundle/issues/4524](https://github.com/sonata-project/SonataAdminBundle/issues/4524)
@jlamur suggested me to reopen the issue in this repository.

### Environment
Linux

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.19.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
 symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.3.2 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

I have an entity 'Examen' which use a trait with 2 fields (costHt and costTtc).
These fields work fine in the methods (configureListFields, configureFormFields, configureShowFields) of ExamenAdmin but raise an error while used in configureDatagridFilters().

```php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')->add('value')->add('certificated')
            ->add('costHt')->add('costTtc');    // <-- raises error
    }
protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')->add('parameter')->add('value')->add('certificated')
            ->add('costHt')->add('costTtc')  // <-- works fine
        ;
    }
```

## Steps to reproduce

Create an entity 'Entity'
Create a trait 'Able' with doctrine fields
Use the trait 'Able' in the entity 'Entity'
Create EntityAdmin class
Configure DatagridFilters with 'Able' fields

## Expected results

I expect required fields added to filter

## Actual results

**Notice: Undefined index: costHt**
Here is the stacktrace after error detection.

-in vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php (line 69)
FilterTypeGuesser->guessType('AppBundle\\Entity\\Examen', 'costHt', object(ModelManager))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 55)
TypeGuesserChain->Sonata\AdminBundle\Guesser\{closure}(object(FilterTypeGuesser))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 73)
TypeGuesserChain->guess(object(Closure))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 56)
TypeGuesserChain->guessType('AppBundle\\Entity\\Examen', 'costHt', object(ModelManager))
-in vendor/sonata-project/doctrine-orm-admin-bundle/Builder/DatagridBuilder.php (line 105)
DatagridBuilder->addFilter(object(Datagrid), null, object(FieldDescription), object(ExamenAdmin))
-in vendor/sonata-project/admin-bundle/Datagrid/DatagridMapper.php (line 89)
DatagridMapper->add('costHt')
-in src/AdminBundle/Admin/ExamenAdmin.php (line 23)

For more, please follow the discussion [https://github.com/sonata-project/SonataAdminBundle/issues/4524](https://github.com/sonata-project/SonataAdminBundle/issues/4524 )

### PR DESCRIPTION
**Pull request by OskarStark**
I am targeting this branch, because this is BC.

Closes #599
Closes #695 

## Changelog

```markdown
### Added
- Added `MissingPropertyMetadataException` if property name is not found in field mappings
```

## Subject

throw `MissingPropertyMetadataException` if propertyName could not be found in mappings

This is based on: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/599/files#r69381571

### CODE REVIEW

File: Model/MissingPropertyMetadataException.php [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+    public function __construct($class, $property)
+    {
+        parent::__construct(sprintf(
+            'No metadata found for property `%s::$%s`.'
+            . ' Please make sure your Doctrine mapping is properly configured.',
+            $class,
+            $property
+        ));
+    }
+}
```
Comment (greg0ire) [inline Model/MissingPropertyMetadataException.php]: Please configure your IDE to always add a newline at end of file, this will make the red pictogram disappear.

Comment (OskarStark) [inline Model/MissingPropertyMetadataException.php]: done

**Comment by jordisala1991** [comment]
Can you add some tests?

**Comment by jordisala1991** [comment]
Are you sure this is not BR Break? Can't you add something like 'relation.field' to the form mapping? Will this PR break this case?

**Comment by OskarStark** [comment]
> Can you add some tests?

to be honest, i don't really know how to test this, can you support me or add a test to my feature branch?

**Comment by jordisala1991** [comment]
I see two options for testing this:

Create a test entity with mapping configuration and do this test without mocking modelManager. Not sure if this one is possible because it wont be a unit test.

Get a simple metadata doing a vardump on normal execution and mock that to test. Probably easier to do. 

I can help with it but it will take some time, because I want to finish FOSUser PR first. 😔

**Comment by OskarStark** [comment]
> I can help with it but it will take some time, because I want to finish FOSUser PR first.

would be great, and don't hurry, FosUser2.0 is more important!

File: Model/MissingPropertyMetadataException.php [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ *
+ * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\DoctrineORMAdminBundle\Model;
+
+class MissingPropertyMetadataException extends \LogicException
```
Comment (core23) [inline Model/MissingPropertyMetadataException.php]: final?

Comment (Soullivaneuh) [inline Model/MissingPropertyMetadataException.php]: Missing author tag.

**Comment by Soullivaneuh** [comment]
Regarding the issue, this is a patch for a fix. Also the changelog need an update.

**Comment by greg0ire** [comment]
I'm working on a failing test for this

**Comment by greg0ire** [comment]
See https://github.com/OskarStark/SonataDoctrineORMAdminBundle/pull/1/files#diff-af7e276869f62cee464f8e6dba88482e

**Comment by OskarStark** [comment]
Thank you @greg0ire, I requested a little change, afterwards I will merge the test-PR on my repo and will apply the comments here 👍

**Comment by greg0ire** [comment]
@OskarStark done

File: Tests/Guesser/FilterTypeGuesserTest.php [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+
+    protected function setUp()
+    {
+        $this->guesser = new FilterTypeGuesser();
+        $this->modelManager = $this->prophesize('Sonata\DoctrineORMAdminBundle\Model\ModelManager');
+        $this->metadata = $this->prophesize('Doctrine\ORM\Mapping\ClassMetadata');
+    }
+
+    /**
+     * @expectException Sonata\DoctrineORMAdminBundle\Model\MissingPropertyMetadataException
```
Comment (greg0ire) [inline Tests/Guesser/FilterTypeGuesserTest.php]: Ok so now that you've merged this, is it really how we usually do it? Or do we have something that transforms `setExceptedException()` to `expectException()`?

File: Model/MissingPropertyMetadataException.php [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+ */
+
+namespace Sonata\DoctrineORMAdminBundle\Model;
+
+/**
+ * @author Oskar Stark <oskarstark@googlemail.com>
+ */
+final class MissingPropertyMetadataException extends \LogicException
+{
+    public function __construct($class, $property)
```
Comment (Soullivaneuh) [inline Model/MissingPropertyMetadataException.php]: Missing PHPDoc

Comment (OskarStark) [inline Model/MissingPropertyMetadataException.php]: done

File: Tests/Guesser/FilterTypeGuesserTest.php (hunk 3 above)
Comment (greg0ire) [inline Tests/Guesser/FilterTypeGuesserTest.php]: ping @OskarStark

Comment (OskarStark) [inline Tests/Guesser/FilterTypeGuesserTest.php]: as this one is deprecated I would recommend to use the annotation!

WDYT @sonata-project/contributors ?

Comment (greg0ire) [inline Tests/Guesser/FilterTypeGuesserTest.php]: How about using `expectException()`, and have that map to `setExpectedException()` in a parent class? `expectException()` is what we should use in next major versions.

Comment (OskarStark) [inline Tests/Guesser/FilterTypeGuesserTest.php]: ah then I don't get it... sorry, my fault

I thought the setExpectedException method is deprecated in favor of the annotation...

Comment (greg0ire) [inline Tests/Guesser/FilterTypeGuesserTest.php]: The issue is that `expectException()` is not available with old phpunit versions. IIRC we solved this issue already.

Comment (greg0ire) [inline Tests/Guesser/FilterTypeGuesserTest.php]: Apparently we recommend `setExpectedException` https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#the-tests

Should be easier to migrate from that than from the annotations.

**Comment by greg0ire** [comment]
Thanks @OskarStark !

**Comment by Soullivaneuh** [comment]
Next time please update the changelog for the fixed part, as asked.

**Comment by OskarStark** [comment]
Released in [3.1.6](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/releases/tag/3.1.6)
