### PR TITLE
Concat value of complex primary key for correct calculate total pages in Datagrid

### LINKED ISSUE #497: Incorrect count query for entities with complex primary key.
I've got bad behavior of [`Pager`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/76100a375997a8151fcb6f436be1f30b3f1c1339/Datagrid/Pager.php#L23) when working with Entities with complex primary key.

[`computeNbResult()`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/76100a375997a8151fcb6f436be1f30b3f1c1339/Datagrid/Pager.php#L30) method counts table entries only by one `DISTINCT` field.

``` php
$countQuery->select(sprintf('count(DISTINCT %s.%s) as cnt', $countQuery->getRootAlias(), current($this->getCountColumn())));
```

But if this field is not unique attribute of entry, `COUNT()` result will be wrong.

### PR DESCRIPTION
**Pull request by peter-gribanov**
## Subject

Closes #497

## Changelog

```markdown
### Fixed
- Concat value of complex primary key for correct calculate total pages in Datagrid
```

### CODE REVIEW

**Comment by peter-gribanov** [comment]
Doctrine considers this DQL invalid
> SELECT count(DISTINCT concat(ub.user,:concat_separator,ub.browserId)) as cnt FROM Sonata\DoctrineORMAdminBundle\Tests\Fixtures\Entity\ORM\UserBrowser ub

Error message

> Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 32 near 'user,:concat_separator,ub.browserId))': Error: Invalid PathExpression. Must be a StateFieldPathExpression.

Maybe related with https://github.com/doctrine/orm/issues/5544

File: src/Datagrid/Pager.php [hunk 1]
```diff
@@ -38,12 +40,32 @@ public function computeNbResult()
             $countQuery->setParameters($this->getParameters());
         }
 
-        $countQuery->select(sprintf(
-            'count(%s %s.%s) as cnt',
-            $countQuery instanceof ProxyQuery && !$countQuery->isDistinct() ? null : 'DISTINCT',
-            current($countQuery->getRootAliases()),
-            current($this->getCountColumn())
-        ));
+        if (\count($this->getCountColumn()) > 1) {
```
Comment (core23) [inline src/Datagrid/Pager.php]: Can you please try to split this method

**Comment by peter-gribanov** [comment]
> Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 32 near 'user,:concat_separator,ub.browserId))': Error: Invalid PathExpression. Must be a StateFieldPathExpression.

The problem was that `ub.user` is an entity and an object cannot be used in function `CONCAT()`.

File: src/Datagrid/Pager.php (hunk 1 above)
Comment (peter-gribanov) [reply src/Datagrid/Pager.php]: I split code of build count query for composite and single primary keys

File: src/Datagrid/Pager.php [hunk 2]
```diff
@@ -23,6 +24,8 @@
  */
 class Pager extends BasePager
 {
+    private const CONCAT_SEPARATOR = '|';
```
Comment (peter-gribanov) [inline src/Datagrid/Pager.php]: Use separator in `CONCAT()` function for correct determinate similar records like:

| id1 | id2 |
| -- | -- |
| A | AA |
| AA | A |

| concat | concat with separator |
| -- | -- |
| AAA | A\|AA |
| AAA | AA\|A |

Comment (OskarStark) [reply src/Datagrid/Pager.php]: Could it make sense to make the const public in case someone extends the `Pager` ?

Comment (peter-gribanov) [reply src/Datagrid/Pager.php]: I think yes. I changed it.

Comment (OskarStark) [reply src/Datagrid/Pager.php]: Thanks

**Comment by VincentLanglet** [comment]
@core23 You requested changes, is it ok for you now ? :)

File: src/Datagrid/Pager.php [hunk 3]
```diff
@@ -23,6 +24,11 @@
  */
 class Pager extends BasePager
 {
+    /**
+     * Use separator in CONCAT() function for correct determinate similar records.
+     */
+    public const CONCAT_SEPARATOR = '|';
```
Comment (core23) [inline src/Datagrid/Pager.php]: Why is this public?

Comment (peter-gribanov) [reply src/Datagrid/Pager.php]: This was requested by @OskarStark https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/996#discussion_r388132758

File: tests/Datagrid/PagerTest.php [hunk 4]
```diff
@@ -29,7 +28,6 @@ public function testComputeNbResultFoCompositeId(): void
     {
         $em = DoctrineTestHelper::createTestEntityManager();
         $classes = [
-            $em->getClassMetadata(User::class),
```
Comment (VincentLanglet) [inline tests/Datagrid/PagerTest.php]: There is a typo in the test name, and the dataProvider seems useless.

I don't know what the test was testing, but since you've to modify it in order to really test the Composite case, I feel like it was testing the single case.
Since it's modified, we don't have tests for single case anymore. Can u add one ?

Comment (peter-gribanov) [reply tests/Datagrid/PagerTest.php]: i restore test single identifier

File: tests/Datagrid/PagerTest.php [hunk 5]
```diff
@@ -25,27 +25,37 @@
...
+        return [
+            [User::class], // single identifier
+            [UserBrowser::class], // composite identifier
+        ];
+    }
+
+    /**
+     * @dataProvider entityClassDataProvider
+     */
+    public function testComputeNbResultFoCompositeId(string $class_name): void
```
Comment (VincentLanglet) [inline tests/Datagrid/PagerTest.php]:
```suggestion
    public function testComputeNbResultForCompositeId(string $class_name): void
```

File: src/Datagrid/Pager.php [hunk 6]
```diff
@@ -85,4 +90,35 @@ public function init()
             $this->getQuery()->setMaxResults($this->getMaxPerPage());
         }
     }
+
+    private function countCompositePrimaryKey(ProxyQueryInterface $countQuery)
+    {
+        $root_aliases = current($countQuery->getRootAliases());
```
Comment (phansys) [inline src/Datagrid/Pager.php]:
```suggestion
        $rootAliases = current($countQuery->getRootAliases());
```

File: src/Datagrid/Pager.php [hunk 7]
```diff
@@ -85,4 +90,35 @@ public function init()
...
+                $columns[] = ':concat_separator';
+            }
+
+            $columns[] = sprintf('%s.%s', $root_aliases, $column);
+        }
+
+        $countQuery->select(sprintf(
+            'count(%s concat(%s)) as cnt',
+            $countQuery instanceof ProxyQuery && !$countQuery->isDistinct() ? null : 'DISTINCT',
+            implode(',', $columns)
```
Comment (phansys) [inline src/Datagrid/Pager.php]:
```suggestion
            implode(', ', $columns)
```

File: src/Datagrid/Pager.php [hunk 8]
```diff
@@ -85,4 +90,35 @@ public function init()
...
+        $root_aliases = current($countQuery->getRootAliases());
+        $countQuery->setParameter('concat_separator', self::CONCAT_SEPARATOR);
+        $columns = [];
+
+        foreach ($this->getCountColumn() as $column) {
+            if ($columns) {
+                $columns[] = ':concat_separator';
+            }
+
+            $columns[] = sprintf('%s.%s', $root_aliases, $column);
```
Comment (phansys) [inline src/Datagrid/Pager.php]:
```suggestion
            $columns[] = sprintf('%s.%s', $rootAliases, $column);
```

File: tests/Datagrid/PagerTest.php [hunk 9]
```diff
@@ -25,27 +25,37 @@
...
+        return [
+            [User::class], // single identifier
+            [UserBrowser::class], // composite identifier
+        ];
+    }
+
+    /**
+     * @dataProvider entityClassDataProvider
+     */
+    public function testComputeNbResultForCompositeId(string $class_name): void
```
Comment (phansys) [inline tests/Datagrid/PagerTest.php]:
```suggestion
    public function testComputeNbResultForCompositeId(string $className): void
```

File: tests/Datagrid/PagerTest.php [hunk 10]
```diff
@@ -25,27 +25,37 @@
...
     {
         $em = DoctrineTestHelper::createTestEntityManager();
         $classes = [
-            $em->getClassMetadata(User::class),
-            $em->getClassMetadata(UserBrowser::class),
+            $em->getClassMetadata($class_name),
```
Comment (phansys) [inline tests/Datagrid/PagerTest.php]:
```suggestion
            $em->getClassMetadata($className),
```

File: tests/Datagrid/PagerTest.php [hunk 11]
```diff
@@ -25,27 +25,37 @@
...
         ];
         $schemaTool = new SchemaTool($em);
         $schemaTool->createSchema($classes);
 
         $qb = $em->createQueryBuilder()
-            ->select('ub')
-            ->from(UserBrowser::class, 'ub');
+            ->select('e')
+            ->from($class_name, 'e');
```
Comment (phansys) [inline tests/Datagrid/PagerTest.php]:
```suggestion
            ->from($className, 'e');
```

File: tests/Datagrid/PagerTest.php [hunk 12]
```diff
@@ -25,27 +25,37 @@
...
         $pq = new ProxyQuery($qb);
         $pager = new Pager();
-        $pager->setCountColumn($em->getClassMetadata(UserBrowser::class)->getIdentifierFieldNames());
+        $pager->setCountColumn($em->getClassMetadata($class_name)->getIdentifierFieldNames());
```
Comment (phansys) [inline tests/Datagrid/PagerTest.php]:
```suggestion
        $pager->setCountColumn($em->getClassMetadata($className)->getIdentifierFieldNames());
```

File: src/Datagrid/Pager.php [hunk 13]
```diff
@@ -85,4 +90,35 @@ public function init()
...
+        }
+
+        $countQuery->select(sprintf(
+            'count(%s concat(%s)) as cnt',
+            $countQuery instanceof ProxyQuery && !$countQuery->isDistinct() ? null : 'DISTINCT',
+            implode(',', $columns)
+        ));
+    }
+
+    private function countSinglePrimaryKey(ProxyQueryInterface $countQuery)
```
Comment (phansys) [inline src/Datagrid/Pager.php]:
```suggestion
    private function countSinglePrimaryKey(ProxyQueryInterface $countQuery): void
```

File: src/Datagrid/Pager.php [hunk 14]
```diff
@@ -85,4 +90,35 @@ public function init()
             $this->getQuery()->setMaxResults($this->getMaxPerPage());
         }
     }
+
+    private function countCompositePrimaryKey(ProxyQueryInterface $countQuery)
```
Comment (phansys) [inline src/Datagrid/Pager.php]:
```suggestion
    private function countCompositePrimaryKey(ProxyQueryInterface $countQuery): void
```

**Comment by peter-gribanov** [comment]
@phansys thanks :+1:

File: src/Datagrid/Pager.php (hunk 14 above)
Comment (phansys) [reply src/Datagrid/Pager.php]: Is there any reason why we can't use `void` as return type?

Comment (peter-gribanov) [reply src/Datagrid/Pager.php]: It’s strange. I added this change.

**Comment by VincentLanglet** [comment]
@phansys I think you review is needed
